language: php
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.cache/composer/files

php:
  - '7.2'
  - '7.3'
  - 7.4snapshot
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_install:
  - |
    if [[ $NO_CHECK == 1 || $NO_DEV == 1 ]];
      then phpenv config-rm xdebug.ini || echo 'No xdebug config.'
      export COMPOSER_FLAGS="$COMPOSER_FLAGS --no-dev"
    fi
  - test "$TRAVIS_PHP_VERSION" != "nightly" || export COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"

before_script:
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source $COMPOSER_FLAGS

script:
  - composer validate --no-check-all
  - composer phpunit || exit 1
  - composer phpcs
  - composer phpmd
  - composer phpstan
  - composer infection
  - composer coverage


notifications:
  email: false
